[package]
name = "openevt-plugins"
version = "1.0.3"
edition = "2024"
exclude = [
    ".understand-anything/*",
    "assets/*",
    "tests/data/*",
    "tools/**",
    "*.mp4",
    "*.mkv",
    "*.avi",
]
description = "Device plugins to be used with the openevt crate"
license = "MIT"
repository = "https://github.com/richbai90/openevt"
documentation = "https://docs.rs/openevt-plugins"
homepage = "https://github.com/richbai90/openevt"

[dependencies]
ffmpeg-next = { version = "9.0.0", default-features = false, features = [
    "codec",
    "format",
    "software-scaling",
] }
hotpath = "0.23"
serde = { version = "1.0.229", features = ["derive"] }
toml = { version = "1.1.4", features = ["serde"] }
openevt = { version = "1.0.3", default-features = false, features = [
    "devices",
    "plugins",
    "library-link",
], path = "../" }
abi_stable = "0.11.3"
rayon = "1.11"
thiserror = "2.0.19"
pyo3 = { version = "0.29.0", optional = true, features = ["extension-module"] }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
python = ["dep:pyo3"]

[lib]
crate-type = ["rlib", "cdylib"]
