#!/usr/bin/env python3
"""Tune simulator parameters against a lightning video with Optuna.

This uses the ``openevt_plugins`` Rust bindings to run the exact physical ODE
integration during each evaluation. Python extracts frame-to-frame contrast
from the video and scores the events generated by Rust against it.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import numpy as np
import openevt_plugins
import optuna

WIDTH = 160
HEIGHT = 90
EPSILON = 1.0e-4
BASELINE_LUMINANCE = 25.0 / 255.0
DEFAULT_TARGET_ACTIVITY = 0.005


def frames(path: Path):
    command = [
        "ffmpeg",
        "-v",
        "error",
        "-i",
        str(path),
        "-vf",
        f"scale={WIDTH}:{HEIGHT}:flags=bilinear,format=gray",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "gray",
        "pipe:1",
    ]
    process = subprocess.Popen(command, stdout=subprocess.PIPE)
    frame_size = WIDTH * HEIGHT
    try:
        while True:
            payload = process.stdout.read(frame_size)
            if not payload:
                break
            if len(payload) != frame_size:
                raise RuntimeError("ffmpeg returned a truncated video frame")
            yield np.frombuffer(payload, dtype=np.uint8).reshape(HEIGHT, WIDTH)
    finally:
        process.stdout.close()
        result = process.wait()
        if result:
            raise RuntimeError(f"ffmpeg failed with exit code {result}")


def evaluate(
    path: Path, trial: optuna.Trial, target_activity: float
) -> float:
    # Restricted upper bound to prevent scale inflation 
    photocurrent_scale = trial.suggest_float(
        "photocurrent_scale", 0.1, 2.0, log=True
    )
    i_d1_t0 = BASELINE_LUMINANCE * photocurrent_scale
    threshold = trial.suggest_float("threshold", 1.0e-4, 2.0e-2, log=True)
    noise_fe_std = trial.suggest_float("noise_fe_std", 1.0e-6, 2.0e-2, log=True)
    noise_o1_std = trial.suggest_float("noise_o1_std", 1.0e-6, 2.0e-2, log=True)

    config_toml = f"""
photocurrent_scale = {photocurrent_scale:.9g}
i_d1_t0 = {i_d1_t0:.9g}
threshold_on = {threshold:.9g}
threshold_off = {threshold:.9g}
noise_fe_std = {noise_fe_std:.9g}
noise_o1_std = {noise_o1_std:.9g}
"""

    try:
        simulator = openevt_plugins.Simulator(
            str(path), config_toml, WIDTH, HEIGHT
        )
    except ValueError as error:
        raise optuna.TrialPruned(
            f"simulator rejected parameters: {error}"
        ) from error
    except OSError as error:
        raise optuna.TrialPruned(
            f"simulator could not open video: {error}"
        ) from error

    previous = None
    high_polarity_scores = []
    low_noise_scores = []
    concentration_scores = []
    frame_activity = []
    frame_contrast = []

    total_events = 0
    last_timestamp_us = 0

    for index, frame in enumerate(frames(path)):
        try:
            batch = simulator.next_batch()
        except OSError:
            break

        batch_size = len(batch)
        total_events += batch_size

        if batch_size > 0:
            last_timestamp_us = max(last_timestamp_us, batch[-1][3])

        elapsed_s = last_timestamp_us / 1_000_000.0

        # Prune if the trial exceeds the 20 MEv/s hardware throughput limit.
        # A 0.05s buffer prevents initial division-by-zero artifacts.
        if elapsed_s > 0.05:
            current_rate = total_events / elapsed_s
            if current_rate > 20_000_000:
                raise optuna.TrialPruned(
                    f"simulator saturated: {current_rate:.2e} Ev/s exceeds 20 MEv/s limit"
                )

        if previous is None:
            previous = frame
            continue

        current = frame.astype(np.float32) / 255.0 * photocurrent_scale
        old = previous.astype(np.float32) / 255.0 * photocurrent_scale
        delta = np.log(current + EPSILON) - np.log(old + EPSILON)

        on = np.zeros((HEIGHT, WIDTH), dtype=bool)
        off = np.zeros((HEIGHT, WIDTH), dtype=bool)
        for x, y, polarity, _timestamp in batch:
            if 0 <= x < WIDTH and 0 <= y < HEIGHT:
                if polarity:
                    on[y, x] = True
                else:
                    off[y, x] = True
        event = on | off

        magnitude = np.abs(delta)
        high_cut = np.quantile(magnitude, 0.90)
        low_cut = np.quantile(magnitude, 0.25)
        high = magnitude >= high_cut
        low = magnitude <= low_cut

        frame_activity.append(float(event.mean()))
        frame_contrast.append(float(magnitude.mean()))

        if high.any():
            high_events = event & high
            concentration_scores.append(
                float(high_events.sum() / max(event.sum(), 1))
            )
            high_event_indices = np.flatnonzero(high_events)
            if high_event_indices.size:
                expected_on = delta.flat[high_event_indices] > 0
                observed_on = on.flat[high_event_indices]
                high_polarity_scores.append(
                    float(np.mean(expected_on == observed_on))
                )

        if low.any():
            low_events = event & low
            count = int(low_events.sum())
            if count:
                positive_fraction = float(on[low_events].mean())
                balance = 1.0 - min(abs(positive_fraction - 0.5) * 2.0, 1.0)
                presence = min(count / max(int(low.sum()) * 0.02, 1), 1.0)
                low_noise_scores.append(balance * presence)

        previous = frame
        if index % 100 == 0:
            trial.report(float(np.mean(high_polarity_scores or [0.0])), index)
            if trial.should_prune():
                raise optuna.TrialPruned()

    if not frame_activity:
        raise RuntimeError("video contains fewer than two frames")

    temporal_alignment = np.corrcoef(frame_activity, frame_contrast)[0, 1]
    if not np.isfinite(temporal_alignment):
        temporal_alignment = 0.0

    mean_activity = float(np.mean(frame_activity))
    # Prefer a sparse but non-zero stream. This penalizes both the current
    # noisy solutions and the degenerate all-thresholded-off solution.
    activity_score = float(
        np.exp(-abs(np.log((mean_activity + EPSILON) / target_activity)))
    )
    trial.set_user_attr("mean_activity", mean_activity)
    trial.set_user_attr("activity_score", activity_score)

    return float(
        0.32 * np.mean(high_polarity_scores or [0.0])
        + 0.20 * np.mean(concentration_scores or [0.0])
        + 0.16 * np.mean(low_noise_scores or [0.0])
        + 0.12 * max(temporal_alignment, 0.0)
        + 0.20 * activity_score
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("video", type=Path)
    parser.add_argument("--trials", type=int, default=100)
    parser.add_argument("--study", type=str, default="lightning-simulator")
    parser.add_argument("--output", type=Path, default=Path("lightning-best.toml"))
    parser.add_argument(
        "--target-activity",
        type=float,
        default=DEFAULT_TARGET_ACTIVITY,
        help="desired mean fraction of active pixels per frame (default: 0.005)",
    )
    args = parser.parse_args()

    if not args.video.is_file():
        parser.error(f"video does not exist: {args.video}")
    if not 0.0 < args.target_activity < 1.0:
        parser.error("--target-activity must be between 0 and 1")

    study = optuna.create_study(
        study_name=args.study,
        direction="maximize",
        storage=f"sqlite:///{args.study}.db",
        load_if_exists=True,
    )
    study.optimize(
        lambda trial: evaluate(args.video, trial, args.target_activity),
        n_trials=args.trials,
    )

    best = study.best_trial
    best_scale = best.params["photocurrent_scale"]
    best_threshold = best.params["threshold"]
    final_params = {
        "photocurrent_scale": best_scale,
        "i_d1_t0": BASELINE_LUMINANCE * best_scale,
        "threshold_on": best_threshold,
        "threshold_off": best_threshold,
        "noise_fe_std": best.params["noise_fe_std"],
        "noise_o1_std": best.params["noise_o1_std"],
    }

    lines = [
        f"{name} = {value:.9g}"
        for name, value in sorted(final_params.items())
    ]
    args.output.write_text("\n".join(lines) + "\n")
    print(
        json.dumps(
            {
                "value": best.value,
                "params": final_params,
                "metrics": {
                    "target_activity": args.target_activity,
                    "mean_activity": best.user_attrs.get("mean_activity"),
                    "activity_score": best.user_attrs.get("activity_score"),
                },
            },
            indent=2,
        )
    )
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
